---
# 上传文件到远程主机
- name: ====== 14 ======== publish new war to remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{{GV_TARGET_WAR_PATH}}", dest: "{{GV_REMOTE_DIR}}/{{GV_REMOTE_WAR_NAME}}" }
  when: EV_OPERATION == "publish"

# 回滚文件到远程主机  
- name: ====== 14 ======== rollback old war to remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{{GV_BACKUP_WAR_PATH}}", dest: "{{GV_REMOTE_DIR}}/{{GV_REMOTE_WAR_NAME}}" }
  when: EV_OPERATION == "rollback"