---
# git clone or pull code
- name: ====== 1 ======== git clone or pull code
  git:
    repo: "{{GV_GIR_URL}}"
    dest: "{{GV_GIT_DIR}}"
    version: "{{EV_ENV}}"
    force: yes
    remote: origin
    clone: yes
    update: yes
  register: pull_result
  tags: pull