---

# 删除本地源码
- name: ====== 0 ======== remove old sourcecode in {{GV_GIT_DIR}}
  shell: source /etc/profile && source ~/.bash_profile  && rm -rf {{GV_GIT_DIR}}/*
  
# git clone or pull code
- name: ====== 1 ======== git clone or pull code
  git:
    repo: "{{GV_GIR_URL}}"
    dest: "{{GV_GIT_DIR}}"
    version: "{{EV_BRANCH}}"
    force: yes
    remote: origin
    clone: yes
    update: yes
  register: pull_result
  tags: pull