---

- name: backup & pull & build
  hosts: localhost
  remote_user: ansible
  vars_files: group_vars/vars
  roles:
    # 备份应用
    - role: backup
      when: EV_OPERATION == 'pack'
    # 拉取代码
    - role: pull
      when: EV_OPERATION == 'pack'
    # 编译打包
    - role: build
      when: EV_OPERATION == 'pack'

- name: check
  hosts: localhost
  remote_user: ansible
  vars_files: group_vars/vars
  roles:
    # 检测打包
    - role: check
      when: EV_OPERATION == 'publish' or EV_OPERATION == 'rollback'
      
- name: upload
  hosts: '{{EV_PROFILE}}'
  vars_files: group_vars/vars
  roles:
    # 清理应用
    - role: clean
      when: EV_OPERATION == 'publish' or EV_OPERATION == 'rollback'
    # 上传应用
    - role: upload
      when: EV_OPERATION == 'publish' or EV_OPERATION == 'rollback'
