---

- name: pull & build
  hosts: localhost
  remote_user: ansible
  vars_files: group_vars/vars
  roles:
    # 拉取代码
    - role: pull
      when: EV_OPERATION == 'deploy'
    # 编译打包
    - role: build
      when: EV_OPERATION == 'deploy'
      
- name: upload
  hosts: '{{EV_HOSTS}}'
  vars_files: group_vars/vars
  roles:
    # 清理应用
#    - role: clean
#      when: EV_OPERATION == 'publish'
    # 上传应用
    - role: upload
      when: EV_OPERATION == 'publish'
