---
# 检查旧包是否存在
- name: ====== check last package file exists ========
  stat:
    path: "{{GV_BACKUP_WAR_PATH}}"
  register: check_last_package_file

# 检查新包是否存在
- name: ====== check this package file exists ======== 
  stat:
    path: "{{GV_TARGET_WAR_PATH}}"
  register: check_this_package_file

# 获取远程服务器应用的pid
- name: ====== 8 ======== grep application pid
  shell: "ps -ef | grep -v grep | grep {{GV_REMOTE_TOMCAT_HOME}} | awk '{print $2}'"
  register: application_processor and EV_OPERATION== 'stop' or (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)

# 发送终止信号
- name: ====== 9 ======== send msg to kill processes
  shell: "kill -15 {{item.pid}}"
  ignore_errors: yes
  with_items:
  - { pid: "{{application_processor.stdout}}"}
  when: application_processor.stdout != '' and EV_OPERATION== 'stop' or (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)

# 等待线程终止
- name: ====== 10 ======== wait 60s for close processes
  wait_for:
    path: "/proc/{{ item.pid }}/status"
    state: absent
    timeout: 60
  ignore_errors: yes
  with_items:
  - { pid: "{{application_processor.stdout}}"}
  when: application_processor.stdout != '' and EV_OPERATION== 'stop' or (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)

# 再次判断线程是否存活着
- name: ====== 11 ======== retry grep application pid
  shell: "ps -ef | grep -v grep | grep {{GV_REMOTE_TOMCAT_HOME}} | awk '{print $2}'"
  register: force_kill_processor
  when: application_processor.stdout != '' and EV_OPERATION== 'stop' or (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)

# 强制杀死进程
- name: ====== 12 ======== force kill processes
  shell: "kill -9 {{item.pid}}"
  ignore_errors: yes
  with_items:
  - { pid: "{{application_processor.stdout}}"}
  when: application_processor.stdout != '' and force_kill_processor.stdout != '' and EV_OPERATION== 'stop' or (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)
