---

# 清理tomcat中的旧包
- name: ====== 13 ======== remove old war in tomcat/deploy/
  shell: "rm -rf {{GV_REMOTE_TOMCAT_HOME}}/deploy/{{GV_WAR_NAME}}*"
  when: check_last_package_file.stat.exists or check_this_package_file.stat.exists