---
- name: echo3
  debug: msg="{{hostvars['localhost']['check_last_package_file']}}"
- name: echo4
  debug: msg="{{hostvars['localhost']['check_this_package_file']}}"
      
# 清理tomcat中的旧包
- name: ====== 13 ======== remove old war in tomcat/deploy/
  shell: "rm -rf {{GV_REMOTE_TOMCAT_HOME}}/deploy/{{GV_WAR_NAME}}*"
  when: hostvars['localhost']['check_last_package_file'].stat.exists or hostvars['localhost']['check_this_package_file'].stat.exists