---

- name: pull & build
  hosts: localhost
  remote_user: ansible
  vars_files: group_vars/vars
  roles:
      # 拉取代码
    - role: pull
      when: EV_OPERATION == 'deploy'
      # 编译打包文件
    - role: build
      when: EV_OPERATION == 'deploy'
