---
# 检查包是否存在
- name: ====== check package exists ======== checking
  stat:
    path: "{% if (EV_OPERATION == \"publish\") %}{{GV_TARGET_WAR_PATH}}{% elif(EV_OPERATION == \"rollback\") %}{{GV_BACKUP_WAR_PATH}}{% else %}{{GV_TARGET_WAR_PATH}}{% endif %}"
  register: check_package
# 打印信息
- name: ====== check package exists ======== print debug
  debug: 
    msg: "{{check_package}}" 
# 执行终止
- name: ====== check package exists ======== stop exe
  fail:
    msg: "Package is not exists!"
  when: (EV_OPERATION == 'publish' and check_package.stat.exists == false) or (EV_OPERATION == 'rollback' and check_package.stat.exists == false)