---
# 检查旧包是否存在
- name: ====== check last package file exists ========
  stat:
    path: "{{GV_BACKUP_WAR_PATH}}"
  register: check_last_package_file
  
- name: ====== print check last package file exists ========
  debug: 
    msg: "{{check_last_package_file.stat.exists}}" 

# 检查新包是否存在
- name: ====== check this package file exists ======== 
  stat:
    path: "{{GV_TARGET_WAR_PATH}}"
  register: check_this_package_file
  
- name: ====== print check this package file exists ========
  debug: 
    msg: "{{check_this_package_file.stat.exists}}" 
    
- name: ====== cancel exe ========
  fail:
    msg: "package is not exists!"
  when: (EV_OPERATION== 'publish' and check_this_package_file.stat.exists) or (EV_OPERATION== 'rollback' and check_last_package_file.stat.exists)