---

# 清理catalina.out
- name: ====== 18 ======== clean catalina.out
  shell: "source /etc/profile && source ~/.bash_profile && nohup echo \"\" > {{GV_REMOTE_TOMCAT_HOME}}/logs/catalina.out &"

# 启动应用
- name: ====== 19 ======== start application
  shell: "source /etc/profile && source ~/.bash_profile && nohup {{GV_REMOTE_TOMCAT_HOME}}/bin/startup.sh &"