---
# 上传新包
- name: ====== 5 ======== upload new package to remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{{GV_MODULE_PACKAGE_PATH}}", dest: "{{GV_REMOTE_DIR}}" }
  
# 解压新包
- name: ====== 6 ======== unzip new package
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    creates: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - { src: "{{GV_REMOTE_DIR}}/{{GV_MODULE_PACKAGE}}", dest: "{{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}" }
  
# 删除新包
- name: ====== 7 ======== remove new package
  shell: "source /etc/profile && source ~/.bash_profile && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_PACKAGE}}"
  
# 更新config.js
- name: ====== 8 ======== update config.js by env
  shell: |
    cp {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config-{{EV_ENV}}.js {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config.js
    rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config-*.js
  register: shell_output
- debug: msg="{{shell_output.stdout_lines}}"