---
# 上传新包
- name: ====== 6 ======== upload new package to remote:{{GV_REMOTE_DIR}}
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{{GV_MODULE_PACKAGE_PATH}}", dest: "{{GV_REMOTE_DIR}}" }
  
# 解压新包
- name: ====== 7 ======== uncompress new package
  shell: "source /etc/profile && source ~/.bash_profile && tar -zxvf {{GV_MODULE_PACKAGE}} && mv {{GV_MODULE_DIR}} {{GV_MODULE_NAME}}"
  args:
    chdir: "{{GV_REMOTE_DIR}}"
#- name: ====== 7 ======== uncompress new package
#  shell: "tar -zxvf {{GV_MODULE_PACKAGE}} && mv {{GV_MODULE_DIR}} {{GV_MODULE_NAME}}"
#  args:
#    chdir: "{{GV_REMOTE_DIR}}"
  
# 删除新包
- name: ====== 8 ======== remove new package
  shell: "source /etc/profile && source ~/.bash_profile && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_PACKAGE}}"
  
# 更新config.js
- name: ====== 9 ======== update config.js by env
  shell: "source /etc/profile && source ~/.bash_profile && cp {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config-{{EV_ENV}}.js {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config.js && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/config-*.js"
  
# 更新首页背景图
- name: ====== 10 ======== update background image if env not in '78' and '79'
  shell: "source /etc/profile && source ~/.bash_profile && mv {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/image/imgtest.jpg {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/image/img.jpg"
  when: ({{EV_ENV}} != "78") and ({{EV_ENV}} != "79")