---
# 上传文件到远程主机
- name: ====== 13 ======== upload package to remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{% if (EV_OPERATION == \"publish\") %}{{GV_TARGET_PACKAGE_PATH}}{% elif(EV_OPERATION == \"rollback\") %}{{GV_BACKUP_PACKAGE_PATH}}{% else %}{{GV_TARGET_PACKAGE_PATH}}{% endif %}", dest: "{{GV_REMOTE_DIR}}/{{GV_REMOTE_PACKAGE_NAME}}" }
  
# 解压包
- name: ====== 14 ======== unzip package
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - { src: "{{GV_REMOTE_DIR}}/{{GV_REMOTE_PACKAGE_NAME}}", dest: "{{GV_REMOTE_DIR}}" }
  
# 删除包
- name: ====== 15 ======== remove package
  shell: "source /etc/profile && source ~/.bash_profile && rm -rf {{GV_REMOTE_DIR}}/{{GV_REMOTE_PACKAGE_NAME}}"
  
# 更新src/script/config.js
- name: ====== 16 ======== update src/script/config.js by profile
  shell: "source /etc/profile && source ~/.bash_profile && cp {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config_{{EV_PROFILE}}.js {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config.js && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config_*.js"