---
# 上传文件到远程主机
- name: ====== 11 ======== upload package to remote server
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
  with_items:
  - { src: "{{GV_MODULE_PACKAGE_PATH}}", dest: "{{GV_REMOTE_DIR}}" }
  
# 解压包
- name: ====== 12 ======== unzip package
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - { src: "{{GV_REMOTE_DIR}}/{{GV_MODULE_PACKAGE}}", dest: "{{GV_REMOTE_DIR}}" }
  
# 删除包
- name: ====== 13 ======== remove package
  shell: "source /etc/profile && source ~/.bash_profile && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_PACKAGE}}"
  
# 更新src/script/config.js
- name: ====== 14 ======== update src/script/config.js by env
  shell: "source /etc/profile && source ~/.bash_profile && cp {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config_{{EV_PROFILE}}.js {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config.js && rm -rf {{GV_REMOTE_DIR}}/{{GV_MODULE_NAME}}/src/script/config_*.js"